# Prod
@token =eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmZDA3MmRmYTM4MDU2NzlmMTZmZTQxNzM4YzJhM2FkM2Y5MGIyMTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3RvcmVpbm8tbGl2ZWNoYXQiLCJhdWQiOiJzdG9yZWluby1saXZlY2hhdCIsImF1dGhfdGltZSI6MTczMjYzNTcwMiwidXNlcl9pZCI6IkhEN1VxTzcxSFNoMThKSGNxWUpQY3FhSmw3ZDIiLCJzdWIiOiJIRDdVcU83MUhTaDE4SkhjcVlKUGNxYUpsN2QyIiwiaWF0IjoxNzMyNjM1NzAyLCJleHAiOjE3MzI2MzkzMDIsImVtYWlsIjoiY29udGFjdEBzdG9yZWluby5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY29udGFjdEBzdG9yZWluby5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.bjJ-9zmkDj045xBY-5UMCC_C04XsrLmBhWQsJiFBEZa7fiy9xRv60ZcJWjmvaAOup6ol72N9wQsGIgf_9Fwm7c43deQhBUpS9Lv5WjC778O4r26Lo1AVcA--7OgMIZD4GBmF2kjQ2GL_uOz1YKVp9KpU2msMuHEmHwLMi3cMc6D3mDzQGfz9KZvWe__7orwF_VjEe9tsMlkYKg929Exp9HkL7Xr9cisjD_rJct3LRKBeo-_o55Yv16A-G9uKEWcz9i_JBlG3oMSU9CeEAVgaTlagBUbaWTsN7B2UiCe_iN5_MdHbZm1J704acxenrx1gezS9ZXC1VR7lZi6wEhPRjQ
###
GET https://api-stores.storeino.com/api/apps/search/?route=countryblocker
X-Auth-Token: {{token}}

###
POST https://api-stores.storeino.com/api/apps/update/?route=megamenu
Content-Type: application/json
X-Auth-Token: {{token}}

{
    "team": {
        "_id": "650abc8b4436be5412bdk9e4",
        "name": "StoreinoApps",
        "url": "#"
    },
    "config":{

    },
    "images": ["https://storeno.b-cdn.net/market/10-2023/1697109170559.png"],
    "placement": "AFTER_HEADER|BEFORE_FOOTER",
    "adminPlacement": "NONE",
    "isActive": true,
    "autoRenew": false,
    "description": "mega menu application.",
    "name": "MegaMenu",
    "route": "megamenu",
    "expiryDate": "2029-11-07T13:21:57.398Z",
}