# Prod
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZSI6eyJfaWQiOiI2NzFhMGQ4MWJkMTViOTAwMTIyNTY2NDEifSwic291cmNlIjoiVEhFTUVTIiwiaWF0IjoxNzMyNzg1MTI0LCJleHAiOjE3NjQzMjExMjR9.UEKkYnkgkYm0JGKRMuSU18z3xHiuXb4cENcLl4mPohA

###
GET https://api-stores.storeino.world/api/apps/search/?route=megamenu
X-Auth-Token: {{token}}

###
POST https://api-stores.storeino.world/api/apps/update/?route=megamenu
Content-Type: application/json
X-Auth-Token: {{token}}

{
    "team": {
        "name": "StoreinoApps",
        "url": "#"
    },
    "images": ["https://storeno.b-cdn.net/market/10-2023/1697109170559.png"],
    "placement": "BEFORE_HEADER|BEFORE_FOOTER|SIDE_BAR",
    "adminPlacement": "NONE",
    "isActive": true,
    "autoRenew": false,
    "description": "Mega menu app for create menu inside theme, with more items to customitze big menus",
    "name": "MegaMenu",
    "route": "megamenu",
    "expiryDate": "2029-11-07T13:21:57.398Z",
      "config": {
        "menus": [
        ]
      }
}